### ISSUE TITLE
Bump puppetlabs/stdlib version to >=8.0.0

### ISSUE THREAD

**Issue by MasterMind2k** [lelutin/puppet-spamassassin#32]
Hi.

Is is possible to bump puppetlabs/stdlib version to 8.0.0 or newer?

Thanks.

**Comment by lelutin** [comment]
Hi,

Yes that's a good idea! I've tested up to version 9.0.0 with puppet 7 and it works ok. I've just pushed commit c4ca405860ce7642d72e596d184e94d15ed9fc35 which bumps the version of stdlib.

I'll prepare a new version of the module to upload to forge in the coming days

**Comment by lelutin** [comment]
@MasterMind2k I've just published version 3.2.1 on forge which has the version bumps.

Cheers!

**Comment by MasterMind2k** [comment]
Thanks! 

Dne, 09. junij 2023 18:42:03 GMT+02:00, Gabriel Filion ***@***.***> sporoča:
